ALTER TABLE "Note"
ADD COLUMN "reviewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastReviewedAt" TIMESTAMP(3);

ALTER TABLE "NoteRevision"
ADD COLUMN "reviewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastReviewedAt" TIMESTAMP(3);
